In [ ]:
from sklearn.neural_network import MLPRegressor

In [ ]:
from sklearn.datasets import make_regression

In [ ]:
X,y = make_regression(n_samples=100, n_features=4, random_state=1)

In [ ]:
X

array([[ 8.46160648e-01,  3.50545979e-01, -1.31228341e+00,
        -8.59515941e-01],
       [ 6.61020288e-01, -1.20464572e-01, -1.23312074e+00,
         1.79215821e+00],
       [-1.91835552e-01, -7.47158294e-01,  1.69245460e+00,
        -8.87628964e-01],
       [ 1.90465871e+00,  6.59049796e-01, -1.62743834e+00,
         1.11105670e+00],
       [-1.85798186e+00,  1.62765075e+00,  3.38011697e-01,
         1.23616403e+00],
       [-2.36436952e-01,  5.15073614e-01, -2.78253447e+00,
         7.27813500e-01],
       [-6.87172700e-01, -6.71246131e-01, -1.26645989e-02,
        -8.45205641e-01],
       [ 2.18557541e+00, -1.44411381e+00, -5.04465863e-01,
        -1.39649634e+00],
       [ 2.32494559e-01, -3.10116774e-01, -2.43483776e+00,
         6.82551407e-01],
       [-7.81911683e-01,  9.54250872e-02,  9.21450069e-01,
        -4.37508983e-01],
       [-3.86955093e-02,  1.12141771e+00,  4.08900538e-01,
        -1.61577235e+00],
       [-1.27255876e+00,  5.03184813e-01,  1.29322588e+00,
      

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,random_state=1)
regr = MLPRegressor(random_state=1, max_iter=300,activation="relu").fit(X_train, y_train)
y_pred = regr.predict(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [ ]:
regr.score(X_test,y_test)

-0.05653509096512188

In [ ]:
from sklearn import metrics as m
print(m.r2_score(y_test,y_pred))

-0.05653509096512188


In [ ]:
from sklearn.datasets import  fetch_california_housing
dat=fetch_california_housing()
x=dat.data
y=dat.target

In [ ]:
x

array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]])

In [ ]:
import numpy
numpy.shape(x)

(20640, 8)

In [ ]:
y

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=.20)
regr = MLPRegressor(random_state=1, max_iter=300,activation="tanh").fit(X_train, y_train)
y_pred = regr.predict(X_test)

In [ ]:
regr.score(X_test,y_test)

0.5375103897657298

In [ ]:
print(m.r2_score(y_test,y_pred))

0.5375103897657298
